flaskadmin/statistics/routes.py
from flask import Blueprint, render_template, request, abort
from flaskadmin.models import Users, Items, Percent
from datetime import date, timedelta, datetime
from flaskadmin import db
from flask_login import login_required, current_user


stats = Blueprint('stats', __name__, template_folder='templates/statistics')


def is_number(string):
    try:
        float(string)
        return True
    except ValueError:
        return False


@stats.route('/', methods=['GET'])
@login_required
def get_all_users(sort_by=None):
    sort_by = request.args.get('sortby') if sort_by is None else sort_by

    if sort_by == 'day':
        name = 'Пользователи за день'
        users = Users.query.filter(Users.reg_time >= date.today()).all()
    elif sort_by == 'week':
        name = 'Пользователи за неделю'
        today = datetime.now().date()
        start = today - timedelta(days=today.weekday())
        users = Users.query.filter(Users.reg_time >= start).all()
    elif sort_by == 'month':
        name = 'Пользователи за месяц'
        today = date.today()
        start = today.replace(day=1)
        users = Users.query.filter(Users.reg_time >= start).all()
    elif sort_by == 'status':
        name = 'Пользователи выполнившие условия'
        status = True if sort_by == 'status' else False
        users = Users.query.filter_by(status=status).all()
    else:
        name = 'Все пользователи'
        users = Users.query.all()
    users_data = list()

    sum_balance = 0
    user_count = len(users)

    for user in users:
        user_data = {'id': user.id, 'user_name': user.user_name, 'balance': user.balance,
                     'rate': user.rate, 'address': user.address, 'invest': user.invest
                     }
        sum_balance += user.balance
        users_data.append(user_data)

    general_info = {'sum_balance': sum_balance, 'user_count': user_count}
    return render_template('users.html', users_data=users_data, general_info=general_info, name=name)


@stats.route('/user/<uid>', methods=['GET', 'POST'])
@login_required
def edit(uid):
    user = Users.query.filter_by(id=uid).first()

    if user is not None and request.method == 'POST':
        balance = request.form.get("balance")
        investor = request.form.get("investor")

        if is_number(balance) and (investor == '0' or investor == '1'):

            investor = True if investor == '1' else False

            user.balance = balance
            user.invest = investor

            if user.status is False and investor is True:
                user.status = True

            db.session.commit()
        else:
            abort(404)

    return render_template('edit.html', user=user)


@stats.route('/items', methods=['GET', 'POST'])
@login_required
def edit_items():
    items = Items.query.all()

    if items is not None and request.method == 'POST':
        texts = request.form.getlist("btntext")
        j = 0

        for item in items:
            item.btn_text = texts[j]
            j += 1

        db.session.commit()

    return render_template('edit_items.html', items=items)


@stats.route('/percent', methods=['GET', 'POST'])
@login_required
def edit_percent():
    percent = Percent.query.all()

    if percent is not None and request.method == 'POST':
        values = request.form.getlist("percents")
        j = 0

        for per in percent:
            per.per_count = values[j]
            j += 1

        db.session.commit()

    return render_template('edit_percent.html', percent=percent)

flaskadmin/statistics/templates/statistics/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Limitless - Responsive Web Application Kit by Eugene Kopyov</title>

	<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
	<link href="{{url_for('static',filename='css/icons/icomoon/styles.min.css')}}" rel="stylesheet" type="text/css">
	<link href="{{url_for('static',filename='css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
	<link href="{{url_for('static',filename='css/bootstrap_limitless.min.css')}}" rel="stylesheet" type="text/css">
	<link href="{{url_for('static',filename='css/layout.min.css')}}" rel="stylesheet" type="text/css">
	<link href="{{url_for('static',filename='css/components.min.css')}}" rel="stylesheet" type="text/css">
	<link href="{{url_for('static',filename='css/colors.min.css')}}" rel="stylesheet" type="text/css">
	<!-- /global stylesheets -->

	<!-- Core JS files -->
	<script src="{{url_for('static',filename='js/main/jquery.min.js')}}"></script>
	<script src="{{url_for('static',filename='js/main/bootstrap.bundle.min.js')}}"></script>
	<script src="{{url_for('static',filename='js/plugins/loaders/blockui.min.js')}}"></script>
	<script src="{{url_for('static',filename='js/plugins/ui/ripple.min.js')}}"></script>
	<!-- /core JS files -->

	<!-- Theme JS files -->
	<script src="{{url_for('static',filename='js/plugins/tables/datatables/datatables.min.js')}}"></script>
	<script src="{{url_for('static',filename='js/plugins/forms/selects/select2.min.js')}}"></script>

	<script src="{{url_for('static',filename='js/app.js')}}"></script>
	<script src="{{url_for('static',filename='js/plugins/demo_pages/datatables_basic.js')}}"></script>

</head>

<body>

	<!-- Main navbar -->
	<div class="navbar navbar-expand-md navbar-dark bg-indigo navbar-static">
		<div class="navbar-brand">
<!--            <img src="{{url_for('static',filename='images/logo_light.png')}}" alt="">-->
		</div>

		<div class="d-md-none">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
				<i class="icon-tree5"></i>
			</button>
			<button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
				<i class="icon-paragraph-justify3"></i>
			</button>
		</div>

		<div class="collapse navbar-collapse" id="navbar-mobile">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
						<i class="icon-paragraph-justify3"></i>
					</a>
				</li>
			</ul>

			<ul class="navbar-nav ml-md-auto">

				<li class="nav-item">
					<a href="{{ url_for('auth.logout') }}" class="navbar-nav-link">
						<i class="icon-switch2"></i>
						<span class="d-md-none ml-2">Logout</span>
					</a>
				</li>
			</ul>
		</div>
	</div>
	<!-- /main navbar -->


	<!-- Page content -->
	<div class="page-content">

		<!-- Main sidebar -->
		<div class="sidebar sidebar-light sidebar-main sidebar-expand-md">

			<!-- Sidebar mobile toggler -->
			<div class="sidebar-mobile-toggler text-center">
				<a href="#" class="sidebar-mobile-main-toggle">
					<i class="icon-arrow-left8"></i>
				</a>
				Navigation
				<a href="#" class="sidebar-mobile-expand">
					<i class="icon-screen-full"></i>
					<i class="icon-screen-normal"></i>
				</a>
			</div>
			<!-- /sidebar mobile toggler -->


			<!-- Sidebar content -->
			<div class="sidebar-content">

				<!-- User menu -->
				<div class="sidebar-user-material">
					<div class="sidebar-user-material-body">
						<div class="card-body text-center">
                            <img src="{{url_for('static',filename='images/placeholders/usdnbot.jpg')}}" class="img-fluid rounded-circle shadow-1 mb-3" width="80" height="80" alt="">
                            <a href="{{ url_for('auth.redact') }}"><h4 class="font-weight-bold text-white">admin <i class="icon-gear"></i></h4></a>
						</div>
					</div>

				</div>
				<!-- /user menu -->


				<!-- Main navigation -->
				<div class="card card-sidebar-mobile">
					<ul class="nav nav-sidebar" data-nav-type="accordion">

						<!-- Main -->
						<li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">ПОЛЬЗОВАТЕЛЬ</div> <i class="icon-menu" title="Main"></i></li>
						<li class="nav-item">
							<a href="{{ url_for('stats.get_all_users') }}" class="nav-link">
								<span>
									Все пользователи
								</span>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ url_for('stats.get_all_users', sortby='day') }}" class="nav-link">
								<span>
									Пользователи за день
								</span>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ url_for('stats.get_all_users', sortby='week') }}" class="nav-link">
								<span>
									Пользователи за неделю
								</span>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ url_for('stats.get_all_users', sortby='month') }}" class="nav-link">
								<span>
									Пользователи за месяц
								</span>
							</a>
						</li>
                        <li class="nav-item">
							<a href="{{ url_for('stats.get_all_users', sortby='status') }}" class="nav-link">
								<span>
									Выполнили условие
								</span>
							</a>
						</li>
						<li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">БОТ</div> <i class="icon-menu" title="Main"></i></li>
						<li class="nav-item">
							<a href="{{ url_for('stats.edit_items') }}" class="nav-link">
								<span>
									Изменить содержимое кнопок
								</span>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ url_for('stats.edit_percent') }}" class="nav-link">
								<span>
									Изменить проценты начислений
								</span>
							</a>
						</li>
					</ul>
				</div>
				<!-- /main navigation -->

			</div>
			<!-- /sidebar content -->

		</div>
		<!-- /main sidebar -->


		<!-- Main content -->
		<div class="content-wrapper">

			<!-- Page header -->
			<div class="page-header page-header-light">
				<div class="page-header-content header-elements-md-inline">
					<div class="page-title d-flex">
                        <h4>Админ-панель телеграм бота <span class="font-weight-semibold">@usdn_bot</span></h4>
					</div>

				</div>

			</div>
			<!-- /page header -->


			<!-- Content area -->
			<div class="content">

				{% block alers %}

				{% endblock alers %}

				<!-- State saving -->
				<div class="card">
					<div class="card-header header-elements-inline">
                            {% block pagename %}

							{% endblock pagename %}
					</div>

							{% block tbody %}

							{% endblock tbody %}

				</div>
				<!-- /state saving -->

			</div>
			<!-- /content area -->


			<!-- Footer -->
			<div class="navbar navbar-expand-lg navbar-light">
				<div class="text-center d-lg-none w-100">
					<button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
						<i class="icon-unfold mr-2"></i>
						Footer
					</button>
				</div>

			<!-- /footer -->

		    </div>
		<!-- /main content -->

	</div>
	<!-- /page content -->

</body>
</html>

flaskadmin/statistics/templates/statistics/edit.html
{% extends 'base.html' %}

{% block alers %}
    {% if request.method == 'POST' %}
        <div class="alert alert-success" role="alert">
            Изменения успешно сохранены!
        </div>
    {% endif %}
{% endblock alers %}

{% block pagename %}
    <h5 class="card-title">Пользователь</h5>
{% endblock pagename %}

{% block tbody %}


<form action="{{ url_for('stats.edit', uid=user.id) }}" method="post" style="padding-left: 20px;">
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Имя</label>
        <div class="col-sm-10">
            <label class="col-form-label">{{ user.user_name }}</label>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Баланс</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="userbalance" name="balance" placeholder="Баланс" value="{{ '%.2f'|format(user.balance) }}">
        </div>
    </div>
    <fieldset class="form-group">
        <div class="row">
            <label class="col-sm-2 col-form-label">Инвестор</label>
            <div class="col-sm-10">
                <div class="form-check">
                    {% if user.invest == True %}
                        <input class="form-check-input" type="radio" name="investor" id="gridRadios1" value="1" checked>
                    {% else %}
                        <input class="form-check-input" type="radio" name="investor" id="gridRadios1" value="1">
                    {% endif %}
                    <label class="form-check-label" for="gridRadios1">
                    Да
                    </label>
                </div>
                <div class="form-check">
                    {% if user.invest == False %}
                        <input class="form-check-input" type="radio" name="investor" id="gridRadios2" value="0" checked>
                    {% else %}
                        <input class="form-check-input" type="radio" name="investor" id="gridRadios2" value="0">
                    {% endif %}
                    <label class="form-check-label" for="gridRadios2">
                    Нет
                    </label>
                </div>
            </div>
        </div>
    </fieldset>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Telegram ID</label>
        <div class="col-sm-10">
            <label class="col-form-label">{{ user.user_id }}</label>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Выполнил условие</label>
        <div class="col-sm-10">
            <span class="{{ 'badge badge-success' if user.status else 'badge badge-danger' }}">{{ 'Да' if user.status else 'Нет' }}</span>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Кол-во приглашенных</label>
        <div class="col-sm-10">
            <label class="col-form-label">{{ user.rate }}</label>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Адрес кошелька</label>
        <div class="col-sm-10">
             <label class="col-form-label">{{ user.address }}</label>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Время регистрации</label>
        <div class="col-sm-10">
            <label class="col-form-label">{{ user.reg_time }}</label>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    </div>
</form>

{% endblock tbody %}

flaskadmin/statistics/templates/statistics/edit_items.html
{% extends 'base.html' %}

{% block alers %}
    {% if request.method == 'POST' %}
        <div class="alert alert-success" role="alert">
            Изменения успешно сохранены!
        </div>
    {% endif %}
{% endblock alers %}

{% block pagename %}
    <h5 class="card-title">Изменить содержимое кнопок</h5>
{% endblock pagename %}

{% block tbody %}


<form action="{{ url_for('stats.edit_items') }}" method="post" style="padding-left: 20px;">
    {% for item in items %}
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">{{ item.btn_name }}</label>
            <div class="col-sm-10">
                <textarea class="form-control" name="btntext" rows="10">{{ item.btn_text }}</textarea>
            </div>
        </div>
    {% endfor %}
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    </div>
</form>

{% endblock tbody %}

flaskadmin/statistics/templates/statistics/edit_percent.html
{% extends 'base.html' %}

{% block alers %}
    {% if request.method == 'POST' %}
        <div class="alert alert-success" role="alert">
            Изменения успешно сохранены!
        </div>
    {% endif %}
{% endblock alers %}

{% block pagename %}
    <h5 class="card-title">Изменить проценты начислений</h5>
{% endblock pagename %}

{% block tbody %}


<form action="{{ url_for('stats.edit_percent') }}" method="post" style="padding-left: 20px;">
    {% for per in percent %}
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">{{ per.per_name }}</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="userbalance" name="percents" placeholder="Баланс" value="{{ per.per_count }}">
            </div>
        </div>
    {% endfor %}
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    </div>
</form>

{% endblock tbody %}

flaskadmin/statistics/templates/statistics/users.html
{% extends 'base.html' %}

{% block pagename %}
    <h5 class="card-title">
        {{ name }}<br>
        Общее кол-во пользователей: {{ general_info.user_count }}<br>
        Суммарное кол-во USDN: {{ '%.2f'|format(general_info.sum_balance) }}
    </h5>
{% endblock pagename %}

{% block tbody %}

    <table class="table datatable-save-state">
        <thead>
            <tr>
                <th>Имя</th>
                <th>Баланс</th>
                <th>Кол-во приглашенных</th>
                <th>Адрес кошелька</th>
                <th>Статус инвестора</th>
                <th class="text-center">Действие</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users_data %}
            <tr>
                <td>{{ user.user_name }}</td>
                <td>{{ "%.2f"|format(user.balance) }}</td>
                <td>{{ user.rate }}</td>
                <td>{{ user.address }}</td>
                <td><span class="{{ 'badge badge-success' if user.invest else 'badge badge-danger' }}">{{ 'Инвестор' if user.invest else 'Обычный' }}</span></td>
                <td class="text-center"><a href="{{ url_for('stats.edit', uid=user.id) }}"><i class="icon-pencil"></i></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock tbody %}